version: 0.2
phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 156041410933.dkr.ecr.us-east-1.amazonaws.com
  pre_build:
    commands:
      - echo Building Docker image...
      - docker build -t blacklist-pipeline .
      - docker tag blacklist-pipeline:latest 156041410933.dkr.ecr.us-east-1.amazonaws.com/blacklist-pipeline:latest
  build:
    commands:
      - echo Running tests with docker-compose...
      - docker-compose up -d db  # Start the database service and wait for it to initialize
      - sleep 15  # Allow time for the database to be ready; adjust as needed
      - docker-compose run --rm test  # Run the tests in the 'test' service
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 156041410933.dkr.ecr.us-east-1.amazonaws.com/blacklist-pipeline:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes
