version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 682033463843.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t devops2024/reposd .
      - docker tag devops2024/reposd:latest 682033463843.dkr.ecr.us-east-1.amazonaws.com/devops2024/reposd:latest     
      - echo Running tests with docker-compose...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 682033463843.dkr.ecr.us-east-1.amazonaws.com/devops2024/reposd:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"682033463843.dkr.ecr.us-east-1.amazonaws.com/devops2024/reposd:latest"}]' > imagedefinitions.json
      - printf '{"ImageUri":"682033463843.dkr.ecr.us-east-1.amazonaws.com/devops2024/reposd:latest"}' > imageDetail.json
      - sed -e 's|<IMAGE1_NAME>|682033463843.dkr.ecr.us-east-1.amazonaws.com/devops2024/reposd:latest|g' taskdef.json > taskdef_processed.json
      - cat imagedefinitions.json
artifacts:
  files:
    - appspec.yaml
    - taskdef_processed.json
    - imageDetail.json
    - imagedefinitions.json
  name: BuildArtifact