version: 0.2
phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 156041410933.dkr.ecr.us-east-1.amazonaws.com
  pre_build:
    commands:
      - echo Building Docker image...
      - docker build -t blacklist-pipeline .
      - docker tag blacklist-pipeline:latest 156041410933.dkr.ecr.us-east-1.amazonaws.com/blacklist-pipeline:latest
  build:
    commands:
      - echo Running tests with docker-compose...
      - docker-compose build  
      - docker-compose up test
      - docker-compose down  # Clean up containers after tests
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 156041410933.dkr.ecr.us-east-1.amazonaws.com/blacklist-pipeline:latest
      - echo Creating imagedefinitions.json for ECS deployment...
      - echo '[{"name":"blacklist_ms_app","imageUri":"156041410933.dkr.ecr.us-east-1.amazonaws.com/blacklist-pipeline:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - '**/*'
  discard-paths: yes